# Source: theia-cloud-crds/templates/workspace-spec-resource.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.theia.cloud
  annotations:
    cert-manager.io/inject-ca-from: default/conversion-webhook-certificate
spec:
  group: theia.cloud
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
    shortNames:
    - ws
  scope: Namespaced
  versions:
    - name : v1beta5
      served: true
      storage: true
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                label:
                  type: string
                appDefinition: # last app definition that ran on this workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user:          # user who created the workspace
                  type: string
                storage:
                  type: string
                options:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
              required:
                - name
                - user
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                volumeClaim:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                volumeAttach:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                error:
                  type: string
          required:
            - spec
    - name : v1beta4
      served: true
      storage: false
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                label:
                  type: string
                appDefinition: # last app definition that ran on this workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user:          # user who created the workspace
                  type: string
                storage:
                  type: string
              required:
                - name
                - user
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                volumeClaim:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                volumeAttach:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                error:
                  type: string
          required:
            - spec
    - name : v1beta3
      served: true
      storage: false
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                label:
                  type: string
                appDefinition: # last app definition that ran on this workspace
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'
                user:          # user who created the workspace
                  type: string
                storage:
                  type: string
                error:
                  type: string
              required:
                - name
                - user
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                volumeClaim:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                volumeAttach:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
          required:
            - spec
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          namespace: default
          name: conversion-webhook-service
          port: 443
          path: /convert/workspace